apiVersion: apps/v1
kind: Deployment
metadata:
  name: goods
spec:
  replicas: 1
  selector:
    matchLabels:
        app: goods
        tire: backend
  template:
    metadata:
      labels:
        app: goods
        tire: backend
    spec:
      containers:
      - name: goods
        image: hw038/back-goods
        env:
        - name: DISTRIBUTOR_HOST
          value: "distributor.default.svc.cluster.local"
        - name: DATABASE_HOST
          value: "hhtestmysql.mariadb.database.azure.com"  # DB 서버 주소
        - name: DATABASE_NAME
          value: "msa"  # MySQL DB 이름 / DB 접속 후 show databases; 입력해서 확인
        - name: DATABASE_USERNAME
          value: "adminuser@hhtestmysql"
        - name: DATABASE_PASSWORD
          value: "qwer1234*"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9010