apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchases
spec:
  replicas: 1
  selector:
    matchLabels:
        app: purchases
        tire: backend
  template:
    metadata:
      labels:
        app: purchases
        tire: backend
    spec:
      containers:
      - name: purchases
        image: hw038/back-purchases
        env:
        - name: DISTRIBUTOR_HOST
          value: "distributor.default.svc.cluster.local"
        - name: DATABASE_HOST
          value: "hhtestmysql.mariadb.database.azure.com"  # DB 서버 주소
        - name: DATABASE_NAME
          value: "msa"  # MySQL DB 이름 / DB 접속 후 show databases; 입력해서 확인
        - name: DATABASE_USERNAME
          value: "adminuser@hhtestmysql"
        - name: DATABASE_PASSWORD
          value: "qwer1234*"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 9030
---
apiVersion: v1
kind: Service
metadata:
  name: purchases
  labels:
    app: purchases
    tire: backend
spec:
  ports:
  - port: 9030
    targetPort: 9030
  selector:
    app: purchases
    tire: backend